language: node_js
node_js:
  - "node"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile
install: npm install
before_script:
  - greenkeeper-lockfile-update
  - npm run build
after_script: greenkeeper-lockfile-upload
deploy:
  skip_cleanup: true
  provider: npm
  email: $EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true
notifications:
  email: false